// 创建命名规则
export const createNamingGroupList = ({
  toCamelCase,
  toConstantCase,
  toDotCase,
  toHeaderCase,
  toKebabCase,
  toPackageCase,
  toPascalCase,
  toPluralKebabCase,
  toPluralSnakeCase,
  toSnakeCase,
}) => {
  const namingGroupList = [
  {
    title: 'JS',
    label: '前端 JS',
    items: [
      { label: '变量', getValue: (name) => toCamelCase(name) },
      { label: '函数', getValue: (name) => toCamelCase(name) },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '私有字段', getValue: (name) => `#${toCamelCase(name)}` },
      { label: '是否布尔', getValue: (name) => `is${toPascalCase(name)}` },
      { label: '拥有布尔', getValue: (name) => `has${toPascalCase(name)}` },
      { label: '可用布尔', getValue: (name) => `can${toPascalCase(name)}` },
      { label: '应当布尔', getValue: (name) => `should${toPascalCase(name)}` },
      { label: '需要布尔', getValue: (name) => `needs${toPascalCase(name)}` },
      { label: '将会布尔', getValue: (name) => `will${toPascalCase(name)}` },
      { label: '获取', getValue: (name) => `get${toPascalCase(name)}` },
      { label: '设置', getValue: (name) => `set${toPascalCase(name)}` },
      { label: '创建', getValue: (name) => `create${toPascalCase(name)}` },
      { label: '读取', getValue: (name) => `read${toPascalCase(name)}` },
      { label: '更新', getValue: (name) => `update${toPascalCase(name)}` },
      { label: '删除', getValue: (name) => `delete${toPascalCase(name)}` },
      { label: '移除', getValue: (name) => `remove${toPascalCase(name)}` },
      { label: '保存', getValue: (name) => `save${toPascalCase(name)}` },
      { label: '加载', getValue: (name) => `load${toPascalCase(name)}` },
      { label: '刷新', getValue: (name) => `refresh${toPascalCase(name)}` },
      { label: '重置', getValue: (name) => `reset${toPascalCase(name)}` },
      { label: '清理', getValue: (name) => `clear${toPascalCase(name)}` },
      { label: '打开', getValue: (name) => `open${toPascalCase(name)}` },
      { label: '关闭', getValue: (name) => `close${toPascalCase(name)}` },
      { label: '切换', getValue: (name) => `toggle${toPascalCase(name)}` },
      { label: '选择', getValue: (name) => `select${toPascalCase(name)}` },
      { label: '提交', getValue: (name) => `submit${toPascalCase(name)}` },
      { label: '校验', getValue: (name) => `validate${toPascalCase(name)}` },
      { label: '解析', getValue: (name) => `parse${toPascalCase(name)}` },
      { label: '格式化', getValue: (name) => `format${toPascalCase(name)}` },
      { label: '序列化', getValue: (name) => `serialize${toPascalCase(name)}` },
      { label: '反序列化', getValue: (name) => `deserialize${toPascalCase(name)}` },
      { label: '归一化', getValue: (name) => `normalize${toPascalCase(name)}` },
      { label: '转换', getValue: (name) => `transform${toPascalCase(name)}` },
      { label: '映射', getValue: (name) => `map${toPascalCase(name)}` },
      { label: '过滤', getValue: (name) => `filter${toPascalCase(name)}` },
      { label: '排序', getValue: (name) => `sort${toPascalCase(name)}` },
      { label: '分组', getValue: (name) => `group${toPascalCase(name)}` },
      { label: '合并', getValue: (name) => `merge${toPascalCase(name)}` },
      { label: '克隆', getValue: (name) => `clone${toPascalCase(name)}` },
      { label: '查找', getValue: (name) => `find${toPascalCase(name)}` },
      { label: '计算', getValue: (name) => `calculate${toPascalCase(name)}` },
      { label: '请求', getValue: (name) => `fetch${toPascalCase(name)}` },
      { label: '异步请求', getValue: (name) => `fetch${toPascalCase(name)}Async` },
      { label: '异步对象', getValue: (name) => `${toCamelCase(name)}Promise` },
      { label: '事件处理', getValue: (name) => `handle${toPascalCase(name)}` },
      { label: '回调属性', getValue: (name) => `on${toPascalCase(name)}` },
      { label: '事件名', getValue: (name) => toKebabCase(name) },
      { label: '事件发射器', getValue: (name) => `${toCamelCase(name)}Emitter` },
      { label: '组件', getValue: (name) => toPascalCase(name) },
      { label: '钩子函数', getValue: (name) => `use${toPascalCase(name)}` },
      { label: '状态钩子', getValue: (name) => `use${toPascalCase(name)}Store` },
      { label: '上下文', getValue: (name) => `${toPascalCase(name)}Context` },
      { label: '提供器', getValue: (name) => `${toPascalCase(name)}Provider` },
      { label: '状态规约器', getValue: (name) => `${toCamelCase(name)}Reducer` },
      { label: '动作对象', getValue: (name) => `${toCamelCase(name)}Action` },
      { label: '选择器', getValue: (name) => `select${toPascalCase(name)}` },
      { label: '引用对象', getValue: (name) => `${toCamelCase(name)}Ref` },
      { label: '缓存值', getValue: (name) => `${toCamelCase(name)}Memo` },
      { label: '类型', getValue: (name) => toPascalCase(name) },
      { label: '属性类型', getValue: (name) => `${toPascalCase(name)}Props` },
      { label: '状态类型', getValue: (name) => `${toPascalCase(name)}State` },
      { label: '选项类型', getValue: (name) => `${toPascalCase(name)}Options` },
      { label: '结果类型', getValue: (name) => `${toPascalCase(name)}Result` },
      { label: '工具函数', getValue: (name) => `${toCamelCase(name)}Util` },
      { label: '服务对象', getValue: (name) => `${toCamelCase(name)}Service` },
      { label: '接口客户端', getValue: (name) => `${toCamelCase(name)}Api` },
      { label: '仓储对象', getValue: (name) => `${toCamelCase(name)}Repository` },
      { label: '控制器', getValue: (name) => `${toCamelCase(name)}Controller` },
      { label: '中间件', getValue: (name) => `${toCamelCase(name)}Middleware` },
      { label: '插件', getValue: (name) => `${toCamelCase(name)}Plugin` },
      { label: '配置对象', getValue: (name) => `${toCamelCase(name)}Config` },
      { label: '结构定义', getValue: (name) => `${toCamelCase(name)}Schema` },
      { label: '传输对象', getValue: (name) => `${toCamelCase(name)}Dto` },
      { label: '模型', getValue: (name) => `${toCamelCase(name)}Model` },
      { label: '错误类', getValue: (name) => `${toPascalCase(name)}Error` },
      { label: '路由路径', getValue: (name) => `/${toKebabCase(name)}` },
      { label: '动态路由', getValue: (name) => `/${toKebabCase(name)}/:id` },
      { label: '查询参数', getValue: (name) => toCamelCase(name) },
      { label: '路径参数', getValue: (name) => `${toCamelCase(name)}Id` },
      { label: '请求头', getValue: (name) => `X-${toHeaderCase(name)}` },
      { label: '权限码', getValue: (name) => toDotCase(name) },
      { label: '功能开关', getValue: (name) => toSnakeCase(name) },
      { label: '环境变量', getValue: (name) => `VITE_${toConstantCase(name)}` },
      { label: '脚本文件', getValue: (name) => `${toKebabCase(name)}.js` },
      { label: '组件文件', getValue: (name) => `${toKebabCase(name)}.jsx` },
      { label: '组件目录', getValue: (name) => `${toPascalCase(name)}/index.jsx` },
      { label: '服务文件', getValue: (name) => `${toKebabCase(name)}.service.js` },
      { label: '钩子文件', getValue: (name) => `use-${toKebabCase(name)}.js` },
      { label: '状态文件', getValue: (name) => `${toKebabCase(name)}.store.js` },
      { label: '测试文件', getValue: (name) => `${toKebabCase(name)}.test.js` },
      { label: '规格测试文件', getValue: (name) => `${toKebabCase(name)}.spec.js` },
      { label: '模拟数据文件', getValue: (name) => `${toKebabCase(name)}.mock.js` },
      { label: '样式类名', getValue: (name) => toKebabCase(name) },
      { label: '样式变量', getValue: (name) => `--${toKebabCase(name)}` },
    ],
  },
  {
    title: 'Java',
    label: '后端 Java',
    items: [
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '接口', getValue: (name) => toPascalCase(name) },
      { label: '抽象类', getValue: (name) => `Abstract${toPascalCase(name)}` },
      { label: '实现类', getValue: (name) => `${toPascalCase(name)}Impl` },
      { label: '方法', getValue: (name) => toCamelCase(name) },
      { label: '字段', getValue: (name) => toCamelCase(name) },
      { label: '是否布尔', getValue: (name) => `is${toPascalCase(name)}` },
      { label: '拥有布尔', getValue: (name) => `has${toPascalCase(name)}` },
      { label: '可用布尔', getValue: (name) => `can${toPascalCase(name)}` },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '枚举值', getValue: (name) => toConstantCase(name) },
      { label: '包名', getValue: (name) => toPackageCase(name) },
      { label: '控制器', getValue: (name) => `${toPascalCase(name)}Controller` },
      { label: '接口控制器', getValue: (name) => `${toPascalCase(name)}RestController` },
      { label: '服务类', getValue: (name) => `${toPascalCase(name)}Service` },
      { label: '服务实现类', getValue: (name) => `${toPascalCase(name)}ServiceImpl` },
      { label: '仓储对象', getValue: (name) => `${toPascalCase(name)}Repository` },
      { label: '映射器', getValue: (name) => `${toPascalCase(name)}Mapper` },
      { label: '数据访问对象', getValue: (name) => `${toPascalCase(name)}Dao` },
      { label: '实体', getValue: (name) => `${toPascalCase(name)}Entity` },
      { label: '聚合根', getValue: (name) => `${toPascalCase(name)}Aggregate` },
      { label: '值对象', getValue: (name) => `${toPascalCase(name)}ValueObject` },
      { label: '传输对象', getValue: (name) => `${toPascalCase(name)}DTO` },
      { label: '视图对象', getValue: (name) => `${toPascalCase(name)}VO` },
      { label: '业务对象', getValue: (name) => `${toPascalCase(name)}BO` },
      { label: '持久对象', getValue: (name) => `${toPascalCase(name)}PO` },
      { label: '领域对象', getValue: (name) => `${toPascalCase(name)}DO` },
      { label: '请求对象', getValue: (name) => `${toPascalCase(name)}Request` },
      { label: '响应对象', getValue: (name) => `${toPascalCase(name)}Response` },
      { label: '命令对象', getValue: (name) => `${toPascalCase(name)}Command` },
      { label: '查询对象', getValue: (name) => `${toPascalCase(name)}Query` },
      { label: '事件对象', getValue: (name) => `${toPascalCase(name)}Event` },
      { label: '监听器', getValue: (name) => `${toPascalCase(name)}Listener` },
      { label: '发布器', getValue: (name) => `${toPascalCase(name)}Publisher` },
      { label: '订阅器', getValue: (name) => `${toPascalCase(name)}Subscriber` },
      { label: '处理器', getValue: (name) => `${toPascalCase(name)}Handler` },
      { label: '工厂', getValue: (name) => `${toPascalCase(name)}Factory` },
      { label: '构建器', getValue: (name) => `${toPascalCase(name)}Builder` },
      { label: '适配器', getValue: (name) => `${toPascalCase(name)}Adapter` },
      { label: '策略', getValue: (name) => `${toPascalCase(name)}Strategy` },
      { label: '校验器', getValue: (name) => `${toPascalCase(name)}Validator` },
      { label: '转换器', getValue: (name) => `${toPascalCase(name)}Converter` },
      { label: '装配器', getValue: (name) => `${toPascalCase(name)}Assembler` },
      { label: '配置对象', getValue: (name) => `${toPascalCase(name)}Config` },
      { label: '配置类', getValue: (name) => `${toPascalCase(name)}Configuration` },
      { label: '配置属性', getValue: (name) => `${toPascalCase(name)}Properties` },
      { label: '过滤器', getValue: (name) => `${toPascalCase(name)}Filter` },
      { label: '拦截器', getValue: (name) => `${toPascalCase(name)}Interceptor` },
      { label: '切面', getValue: (name) => `${toPascalCase(name)}Aspect` },
      { label: '注解', getValue: (name) => toPascalCase(name) },
      { label: '枚举', getValue: (name) => `${toPascalCase(name)}Enum` },
      { label: '异常类', getValue: (name) => `${toPascalCase(name)}Exception` },
      { label: '运行时异常', getValue: (name) => `${toPascalCase(name)}RuntimeException` },
      { label: '客户端', getValue: (name) => `${toPascalCase(name)}Client` },
      { label: '远程客户端', getValue: (name) => `${toPascalCase(name)}FeignClient` },
      { label: '队列任务', getValue: (name) => `${toPascalCase(name)}Job` },
      { label: '任务', getValue: (name) => `${toPascalCase(name)}Task` },
      { label: '定时任务', getValue: (name) => `${toPascalCase(name)}Scheduler` },
      { label: '测试类', getValue: (name) => `${toPascalCase(name)}Test` },
      { label: '集成测试', getValue: (name) => `${toPascalCase(name)}IT` },
      { label: '模拟对象', getValue: (name) => `${toPascalCase(name)}Mock` },
      { label: '测试夹具', getValue: (name) => `${toPascalCase(name)}Fixture` },
      { label: '源码文件', getValue: (name) => `${toPascalCase(name)}.java` },
      { label: '测试文件', getValue: (name) => `${toPascalCase(name)}Test.java` },
      { label: '属性前缀', getValue: (name) => toKebabCase(name) },
      { label: '接口路径', getValue: (name) => `/${toPluralKebabCase(name)}` },
      { label: '权限码', getValue: (name) => toDotCase(name) },
    ],
  },
  {
    title: 'Python',
    label: '脚本 Python',
    items: [
      { label: '变量', getValue: (name) => toSnakeCase(name) },
      { label: '函数', getValue: (name) => toSnakeCase(name) },
      { label: '异步函数', getValue: (name) => `async_${toSnakeCase(name)}` },
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '模块常量', getValue: (name) => toConstantCase(name) },
      { label: '私有成员', getValue: (name) => `_${toSnakeCase(name)}` },
      { label: '强私有成员', getValue: (name) => `__${toSnakeCase(name)}` },
      { label: '魔术方法', getValue: (name) => `__${toSnakeCase(name)}__` },
      { label: '属性', getValue: (name) => toSnakeCase(name) },
      { label: '属性方法', getValue: (name) => toSnakeCase(name) },
      { label: '模块文件', getValue: (name) => `${toSnakeCase(name)}.py` },
      { label: '包目录', getValue: (name) => toSnakeCase(name) },
      { label: '测试文件', getValue: (name) => `test_${toSnakeCase(name)}.py` },
      { label: '测试用例', getValue: (name) => `test_${toSnakeCase(name)}` },
      { label: '测试夹具', getValue: (name) => `${toSnakeCase(name)}_fixture` },
      { label: '模拟对象', getValue: (name) => `${toSnakeCase(name)}_mock` },
      { label: '工厂', getValue: (name) => `${toPascalCase(name)}Factory` },
      { label: '数据模型', getValue: (name) => `${toPascalCase(name)}Model` },
      { label: '结构定义', getValue: (name) => `${toPascalCase(name)}Schema` },
      { label: '创建结构', getValue: (name) => `${toPascalCase(name)}Create` },
      { label: '更新结构', getValue: (name) => `${toPascalCase(name)}Update` },
      { label: '读取结构', getValue: (name) => `${toPascalCase(name)}Read` },
      { label: '设置类', getValue: (name) => `${toPascalCase(name)}Settings` },
      { label: '数据表模型', getValue: (name) => `${toPascalCase(name)}Table` },
      { label: '仓储对象', getValue: (name) => `${toSnakeCase(name)}_repository` },
      { label: '服务类', getValue: (name) => `${toSnakeCase(name)}_service` },
      { label: '路由器', getValue: (name) => `${toSnakeCase(name)}_router` },
      { label: '依赖函数', getValue: (name) => `get_${toSnakeCase(name)}` },
      { label: '中间件', getValue: (name) => `${toSnakeCase(name)}_middleware` },
      { label: '异常类', getValue: (name) => `${toPascalCase(name)}Error` },
      { label: '枚举', getValue: (name) => `${toPascalCase(name)}Enum` },
      { label: '协议类型', getValue: (name) => `${toPascalCase(name)}Protocol` },
      { label: '字典类型', getValue: (name) => `${toPascalCase(name)}Dict` },
      { label: '数据类', getValue: (name) => `${toPascalCase(name)}Data` },
      { label: '异步任务', getValue: (name) => `${toSnakeCase(name)}_task` },
      { label: '管理命令', getValue: (name) => toSnakeCase(name) },
      { label: '迁移脚本', getValue: (name) => `create_${toPluralSnakeCase(name)}_table` },
      { label: '接口路由', getValue: (name) => `/${toKebabCase(name)}` },
      { label: '动态路由', getValue: (name) => `/${toKebabCase(name)}/{${toSnakeCase(name)}_id}` },
      { label: '查询参数', getValue: (name) => toSnakeCase(name) },
      { label: '环境变量', getValue: (name) => toConstantCase(name) },
      { label: '日志字段', getValue: (name) => toSnakeCase(name) },
      { label: '命令行命令', getValue: (name) => toKebabCase(name) },
    ],
  },
  {
    title: 'PHP',
    label: '后端 PHP',
    items: [
      { label: '变量', getValue: (name) => `$${toCamelCase(name)}` },
      { label: '方法', getValue: (name) => toCamelCase(name) },
      { label: '函数', getValue: (name) => toSnakeCase(name) },
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '接口', getValue: (name) => `${toPascalCase(name)}Interface` },
      { label: '特征类', getValue: (name) => `${toPascalCase(name)}Trait` },
      { label: '枚举', getValue: (name) => `${toPascalCase(name)}Enum` },
      { label: '命名空间', getValue: (name) => toPascalCase(name) },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '控制器', getValue: (name) => `${toPascalCase(name)}Controller` },
      { label: '接口控制器', getValue: (name) => `${toPascalCase(name)}ApiController` },
      { label: '服务类', getValue: (name) => `${toPascalCase(name)}Service` },
      { label: '仓储对象', getValue: (name) => `${toPascalCase(name)}Repository` },
      { label: '模型', getValue: (name) => `${toPascalCase(name)}Model` },
      { label: '实体', getValue: (name) => `${toPascalCase(name)}Entity` },
      { label: '传输对象', getValue: (name) => `${toPascalCase(name)}Data` },
      { label: '请求对象', getValue: (name) => `${toPascalCase(name)}Request` },
      { label: '表单请求', getValue: (name) => `${toPascalCase(name)}FormRequest` },
      { label: '资源对象', getValue: (name) => `${toPascalCase(name)}Resource` },
      { label: '集合资源', getValue: (name) => `${toPascalCase(name)}Collection` },
      { label: '中间件', getValue: (name) => `${toPascalCase(name)}Middleware` },
      { label: '权限策略', getValue: (name) => `${toPascalCase(name)}Policy` },
      { label: '权限门面', getValue: (name) => `${toCamelCase(name)}Gate` },
      { label: '队列任务', getValue: (name) => `${toPascalCase(name)}Job` },
      { label: '命令对象', getValue: (name) => `${toPascalCase(name)}Command` },
      { label: '事件对象', getValue: (name) => `${toPascalCase(name)}Event` },
      { label: '监听器', getValue: (name) => `${toPascalCase(name)}Listener` },
      { label: '通知', getValue: (name) => `${toPascalCase(name)}Notification` },
      { label: '邮件', getValue: (name) => `${toPascalCase(name)}Mail` },
      { label: '观察者', getValue: (name) => `${toPascalCase(name)}Observer` },
      { label: '提供器', getValue: (name) => `${toPascalCase(name)}ServiceProvider` },
      { label: '规则', getValue: (name) => `${toPascalCase(name)}Rule` },
      { label: '类型转换', getValue: (name) => `${toPascalCase(name)}Cast` },
      { label: '查询作用域', getValue: (name) => `${toPascalCase(name)}Scope` },
      { label: '工厂', getValue: (name) => `${toPascalCase(name)}Factory` },
      { label: '种子类', getValue: (name) => `${toPascalCase(name)}Seeder` },
      { label: '迁移类', getValue: (name) => `create_${toPluralSnakeCase(name)}_table` },
      { label: '异常类', getValue: (name) => `${toPascalCase(name)}Exception` },
      { label: '测试类', getValue: (name) => `${toPascalCase(name)}Test` },
      { label: '功能测试', getValue: (name) => `${toPascalCase(name)}FeatureTest` },
      { label: '单元测试', getValue: (name) => `${toPascalCase(name)}UnitTest` },
      { label: '源码文件', getValue: (name) => `${toPascalCase(name)}.php` },
      { label: '模板文件', getValue: (name) => `${toKebabCase(name)}.blade.php` },
      { label: '路由名', getValue: (name) => toDotCase(name) },
      { label: '路由路径', getValue: (name) => `/${toKebabCase(name)}` },
      { label: '配置键', getValue: (name) => toDotCase(name) },
      { label: '环境变量', getValue: (name) => toConstantCase(name) },
      { label: '队列名', getValue: (name) => toKebabCase(name) },
    ],
  },
  {
    title: 'SQL',
    label: '数据库 SQL',
    items: [
      { label: '数据库', getValue: (name) => toSnakeCase(name) },
      { label: '结构定义', getValue: (name) => toSnakeCase(name) },
      { label: '表名', getValue: (name) => toPluralSnakeCase(name) },
      { label: '关联表', getValue: (name) => `${toPluralSnakeCase(name)}_relations` },
      { label: '字段名', getValue: (name) => toSnakeCase(name) },
      { label: '主键', getValue: (name) => `${toSnakeCase(name)}_id` },
      { label: '外键', getValue: (name) => `${toSnakeCase(name)}_id` },
      { label: '布尔字段', getValue: (name) => `is_${toSnakeCase(name)}` },
      { label: '状态字段', getValue: (name) => `${toSnakeCase(name)}_status` },
      { label: '类型字段', getValue: (name) => `${toSnakeCase(name)}_type` },
      { label: '数量字段', getValue: (name) => `${toSnakeCase(name)}_count` },
      { label: '金额字段', getValue: (name) => `${toSnakeCase(name)}_amount` },
      { label: '时间字段', getValue: (name) => `${toSnakeCase(name)}_at` },
      { label: '日期字段', getValue: (name) => `${toSnakeCase(name)}_date` },
      { label: '对象字段', getValue: (name) => `${toSnakeCase(name)}_json` },
      { label: '普通索引', getValue: (name) => `idx_${toSnakeCase(name)}` },
      { label: '联合索引', getValue: (name) => `idx_${toSnakeCase(name)}_id` },
      { label: '唯一索引', getValue: (name) => `uk_${toSnakeCase(name)}` },
      { label: '主键约束', getValue: (name) => `pk_${toSnakeCase(name)}` },
      { label: '外键约束', getValue: (name) => `fk_${toSnakeCase(name)}_id` },
      { label: '唯一约束', getValue: (name) => `uq_${toSnakeCase(name)}` },
      { label: '检查约束', getValue: (name) => `ck_${toSnakeCase(name)}` },
      { label: '默认约束', getValue: (name) => `df_${toSnakeCase(name)}` },
      { label: '查询别名', getValue: (name) => toSnakeCase(name) },
      { label: '公共表表达式', getValue: (name) => `${toSnakeCase(name)}_cte` },
      { label: '视图', getValue: (name) => `v_${toSnakeCase(name)}` },
      { label: '物化视图', getValue: (name) => `mv_${toSnakeCase(name)}` },
      { label: '存储过程', getValue: (name) => `sp_${toSnakeCase(name)}` },
      { label: '函数', getValue: (name) => `fn_${toSnakeCase(name)}` },
      { label: '触发器', getValue: (name) => `trg_${toSnakeCase(name)}` },
      { label: '序列', getValue: (name) => `seq_${toSnakeCase(name)}` },
      { label: '临时表', getValue: (name) => `tmp_${toSnakeCase(name)}` },
      { label: '归档表', getValue: (name) => `${toSnakeCase(name)}_archive` },
      { label: '备份表', getValue: (name) => `${toSnakeCase(name)}_bak` },
      { label: '日志表', getValue: (name) => `${toSnakeCase(name)}_logs` },
      { label: '历史表', getValue: (name) => `${toSnakeCase(name)}_histories` },
      { label: '审计表', getValue: (name) => `${toSnakeCase(name)}_audits` },
      { label: '分区表', getValue: (name) => `${toSnakeCase(name)}_partition` },
      { label: '迁移', getValue: (name) => `create_${toPluralSnakeCase(name)}_table` },
      { label: '种子数据', getValue: (name) => `seed_${toPluralSnakeCase(name)}` },
      { label: '回滚脚本', getValue: (name) => `drop_${toPluralSnakeCase(name)}_table` },
      { label: '脚本文件', getValue: (name) => `${toSnakeCase(name)}.sql` },
    ],
  },
];

  return namingGroupList.map((group) => ({
    ...group,
    items: group.items.map((item) => ({
      ...item,
      description: `用于${group.label}场景下的${item.label}命名`,
    })),
  }));
};
