// 创建命名规则
export const createNamingGroupList = ({
  toCamelCase,
  toConstantCase,
  toDotCase,
  toHeaderCase,
  toKebabCase,
  toPackageCase,
  toPascalCase,
  toPluralKebabCase,
  toPluralSnakeCase,
  toSnakeCase,
}) => {
  const namingGroupList = [
  {
    title: 'JS',
    items: [
      { label: '变量', getValue: (name) => toCamelCase(name) },
      { label: '函数', getValue: (name) => toCamelCase(name) },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '私有字段', getValue: (name) => `#${toCamelCase(name)}` },
      { label: 'is 布尔', getValue: (name) => `is${toPascalCase(name)}` },
      { label: 'has 布尔', getValue: (name) => `has${toPascalCase(name)}` },
      { label: 'can 布尔', getValue: (name) => `can${toPascalCase(name)}` },
      { label: 'should 布尔', getValue: (name) => `should${toPascalCase(name)}` },
      { label: 'needs 布尔', getValue: (name) => `needs${toPascalCase(name)}` },
      { label: 'will 布尔', getValue: (name) => `will${toPascalCase(name)}` },
      { label: '获取', getValue: (name) => `get${toPascalCase(name)}` },
      { label: '设置', getValue: (name) => `set${toPascalCase(name)}` },
      { label: '创建', getValue: (name) => `create${toPascalCase(name)}` },
      { label: '读取', getValue: (name) => `read${toPascalCase(name)}` },
      { label: '更新', getValue: (name) => `update${toPascalCase(name)}` },
      { label: '删除', getValue: (name) => `delete${toPascalCase(name)}` },
      { label: '移除', getValue: (name) => `remove${toPascalCase(name)}` },
      { label: '保存', getValue: (name) => `save${toPascalCase(name)}` },
      { label: '加载', getValue: (name) => `load${toPascalCase(name)}` },
      { label: '刷新', getValue: (name) => `refresh${toPascalCase(name)}` },
      { label: '重置', getValue: (name) => `reset${toPascalCase(name)}` },
      { label: '清理', getValue: (name) => `clear${toPascalCase(name)}` },
      { label: '打开', getValue: (name) => `open${toPascalCase(name)}` },
      { label: '关闭', getValue: (name) => `close${toPascalCase(name)}` },
      { label: '切换', getValue: (name) => `toggle${toPascalCase(name)}` },
      { label: '选择', getValue: (name) => `select${toPascalCase(name)}` },
      { label: '提交', getValue: (name) => `submit${toPascalCase(name)}` },
      { label: '校验', getValue: (name) => `validate${toPascalCase(name)}` },
      { label: '解析', getValue: (name) => `parse${toPascalCase(name)}` },
      { label: '格式化', getValue: (name) => `format${toPascalCase(name)}` },
      { label: '序列化', getValue: (name) => `serialize${toPascalCase(name)}` },
      { label: '反序列化', getValue: (name) => `deserialize${toPascalCase(name)}` },
      { label: '归一化', getValue: (name) => `normalize${toPascalCase(name)}` },
      { label: '转换', getValue: (name) => `transform${toPascalCase(name)}` },
      { label: '映射', getValue: (name) => `map${toPascalCase(name)}` },
      { label: '过滤', getValue: (name) => `filter${toPascalCase(name)}` },
      { label: '排序', getValue: (name) => `sort${toPascalCase(name)}` },
      { label: '分组', getValue: (name) => `group${toPascalCase(name)}` },
      { label: '合并', getValue: (name) => `merge${toPascalCase(name)}` },
      { label: '克隆', getValue: (name) => `clone${toPascalCase(name)}` },
      { label: '查找', getValue: (name) => `find${toPascalCase(name)}` },
      { label: '计算', getValue: (name) => `calculate${toPascalCase(name)}` },
      { label: '请求', getValue: (name) => `fetch${toPascalCase(name)}` },
      { label: '异步请求', getValue: (name) => `fetch${toPascalCase(name)}Async` },
      { label: 'Promise', getValue: (name) => `${toCamelCase(name)}Promise` },
      { label: '事件处理', getValue: (name) => `handle${toPascalCase(name)}` },
      { label: '回调属性', getValue: (name) => `on${toPascalCase(name)}` },
      { label: '事件名', getValue: (name) => toKebabCase(name) },
      { label: 'Emitter', getValue: (name) => `${toCamelCase(name)}Emitter` },
      { label: '组件', getValue: (name) => toPascalCase(name) },
      { label: 'Hook', getValue: (name) => `use${toPascalCase(name)}` },
      { label: 'Store Hook', getValue: (name) => `use${toPascalCase(name)}Store` },
      { label: 'Context', getValue: (name) => `${toPascalCase(name)}Context` },
      { label: 'Provider', getValue: (name) => `${toPascalCase(name)}Provider` },
      { label: 'Reducer', getValue: (name) => `${toCamelCase(name)}Reducer` },
      { label: 'Action', getValue: (name) => `${toCamelCase(name)}Action` },
      { label: 'Selector', getValue: (name) => `select${toPascalCase(name)}` },
      { label: 'Ref', getValue: (name) => `${toCamelCase(name)}Ref` },
      { label: 'Memo', getValue: (name) => `${toCamelCase(name)}Memo` },
      { label: 'Type', getValue: (name) => toPascalCase(name) },
      { label: 'Props', getValue: (name) => `${toPascalCase(name)}Props` },
      { label: 'State', getValue: (name) => `${toPascalCase(name)}State` },
      { label: 'Options', getValue: (name) => `${toPascalCase(name)}Options` },
      { label: 'Result', getValue: (name) => `${toPascalCase(name)}Result` },
      { label: '工具函数', getValue: (name) => `${toCamelCase(name)}Util` },
      { label: '服务对象', getValue: (name) => `${toCamelCase(name)}Service` },
      { label: 'API 客户端', getValue: (name) => `${toCamelCase(name)}Api` },
      { label: 'Repository', getValue: (name) => `${toCamelCase(name)}Repository` },
      { label: 'Controller', getValue: (name) => `${toCamelCase(name)}Controller` },
      { label: 'Middleware', getValue: (name) => `${toCamelCase(name)}Middleware` },
      { label: 'Plugin', getValue: (name) => `${toCamelCase(name)}Plugin` },
      { label: 'Config', getValue: (name) => `${toCamelCase(name)}Config` },
      { label: 'Schema', getValue: (name) => `${toCamelCase(name)}Schema` },
      { label: 'DTO', getValue: (name) => `${toCamelCase(name)}Dto` },
      { label: 'Model', getValue: (name) => `${toCamelCase(name)}Model` },
      { label: 'Error 类', getValue: (name) => `${toPascalCase(name)}Error` },
      { label: '路由路径', getValue: (name) => `/${toKebabCase(name)}` },
      { label: '动态路由', getValue: (name) => `/${toKebabCase(name)}/:id` },
      { label: '查询参数', getValue: (name) => toCamelCase(name) },
      { label: '路径参数', getValue: (name) => `${toCamelCase(name)}Id` },
      { label: 'HTTP Header', getValue: (name) => `X-${toHeaderCase(name)}` },
      { label: '权限码', getValue: (name) => toDotCase(name) },
      { label: 'Feature Flag', getValue: (name) => toSnakeCase(name) },
      { label: 'Env 变量', getValue: (name) => `VITE_${toConstantCase(name)}` },
      { label: 'JS 文件', getValue: (name) => `${toKebabCase(name)}.js` },
      { label: 'JSX 文件', getValue: (name) => `${toKebabCase(name)}.jsx` },
      { label: '组件目录', getValue: (name) => `${toPascalCase(name)}/index.jsx` },
      { label: '服务文件', getValue: (name) => `${toKebabCase(name)}.service.js` },
      { label: 'Hook 文件', getValue: (name) => `use-${toKebabCase(name)}.js` },
      { label: 'Store 文件', getValue: (name) => `${toKebabCase(name)}.store.js` },
      { label: '测试文件', getValue: (name) => `${toKebabCase(name)}.test.js` },
      { label: 'Spec 文件', getValue: (name) => `${toKebabCase(name)}.spec.js` },
      { label: 'Mock 文件', getValue: (name) => `${toKebabCase(name)}.mock.js` },
      { label: 'CSS 类名', getValue: (name) => toKebabCase(name) },
      { label: 'CSS 变量', getValue: (name) => `--${toKebabCase(name)}` },
    ],
  },
  {
    title: 'Java',
    items: [
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '接口', getValue: (name) => toPascalCase(name) },
      { label: '抽象类', getValue: (name) => `Abstract${toPascalCase(name)}` },
      { label: '实现类', getValue: (name) => `${toPascalCase(name)}Impl` },
      { label: '方法', getValue: (name) => toCamelCase(name) },
      { label: '字段', getValue: (name) => toCamelCase(name) },
      { label: 'is 布尔', getValue: (name) => `is${toPascalCase(name)}` },
      { label: 'has 布尔', getValue: (name) => `has${toPascalCase(name)}` },
      { label: 'can 布尔', getValue: (name) => `can${toPascalCase(name)}` },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '枚举值', getValue: (name) => toConstantCase(name) },
      { label: '包名', getValue: (name) => toPackageCase(name) },
      { label: 'Controller', getValue: (name) => `${toPascalCase(name)}Controller` },
      { label: 'RestController', getValue: (name) => `${toPascalCase(name)}RestController` },
      { label: 'Service', getValue: (name) => `${toPascalCase(name)}Service` },
      { label: 'ServiceImpl', getValue: (name) => `${toPascalCase(name)}ServiceImpl` },
      { label: 'Repository', getValue: (name) => `${toPascalCase(name)}Repository` },
      { label: 'Mapper', getValue: (name) => `${toPascalCase(name)}Mapper` },
      { label: 'Dao', getValue: (name) => `${toPascalCase(name)}Dao` },
      { label: 'Entity', getValue: (name) => `${toPascalCase(name)}Entity` },
      { label: 'Aggregate', getValue: (name) => `${toPascalCase(name)}Aggregate` },
      { label: 'ValueObject', getValue: (name) => `${toPascalCase(name)}ValueObject` },
      { label: 'DTO', getValue: (name) => `${toPascalCase(name)}DTO` },
      { label: 'VO', getValue: (name) => `${toPascalCase(name)}VO` },
      { label: 'BO', getValue: (name) => `${toPascalCase(name)}BO` },
      { label: 'PO', getValue: (name) => `${toPascalCase(name)}PO` },
      { label: 'DO', getValue: (name) => `${toPascalCase(name)}DO` },
      { label: 'Request', getValue: (name) => `${toPascalCase(name)}Request` },
      { label: 'Response', getValue: (name) => `${toPascalCase(name)}Response` },
      { label: 'Command', getValue: (name) => `${toPascalCase(name)}Command` },
      { label: 'Query', getValue: (name) => `${toPascalCase(name)}Query` },
      { label: 'Event', getValue: (name) => `${toPascalCase(name)}Event` },
      { label: 'Listener', getValue: (name) => `${toPascalCase(name)}Listener` },
      { label: 'Publisher', getValue: (name) => `${toPascalCase(name)}Publisher` },
      { label: 'Subscriber', getValue: (name) => `${toPascalCase(name)}Subscriber` },
      { label: 'Handler', getValue: (name) => `${toPascalCase(name)}Handler` },
      { label: 'Factory', getValue: (name) => `${toPascalCase(name)}Factory` },
      { label: 'Builder', getValue: (name) => `${toPascalCase(name)}Builder` },
      { label: 'Adapter', getValue: (name) => `${toPascalCase(name)}Adapter` },
      { label: 'Strategy', getValue: (name) => `${toPascalCase(name)}Strategy` },
      { label: 'Validator', getValue: (name) => `${toPascalCase(name)}Validator` },
      { label: 'Converter', getValue: (name) => `${toPascalCase(name)}Converter` },
      { label: 'Assembler', getValue: (name) => `${toPascalCase(name)}Assembler` },
      { label: 'Config', getValue: (name) => `${toPascalCase(name)}Config` },
      { label: 'Configuration', getValue: (name) => `${toPascalCase(name)}Configuration` },
      { label: 'Properties', getValue: (name) => `${toPascalCase(name)}Properties` },
      { label: 'Filter', getValue: (name) => `${toPascalCase(name)}Filter` },
      { label: 'Interceptor', getValue: (name) => `${toPascalCase(name)}Interceptor` },
      { label: 'Aspect', getValue: (name) => `${toPascalCase(name)}Aspect` },
      { label: 'Annotation', getValue: (name) => toPascalCase(name) },
      { label: 'Enum', getValue: (name) => `${toPascalCase(name)}Enum` },
      { label: 'Exception', getValue: (name) => `${toPascalCase(name)}Exception` },
      { label: 'RuntimeException', getValue: (name) => `${toPascalCase(name)}RuntimeException` },
      { label: 'Client', getValue: (name) => `${toPascalCase(name)}Client` },
      { label: 'FeignClient', getValue: (name) => `${toPascalCase(name)}FeignClient` },
      { label: 'Job', getValue: (name) => `${toPascalCase(name)}Job` },
      { label: 'Task', getValue: (name) => `${toPascalCase(name)}Task` },
      { label: 'Scheduler', getValue: (name) => `${toPascalCase(name)}Scheduler` },
      { label: 'Test', getValue: (name) => `${toPascalCase(name)}Test` },
      { label: 'IT', getValue: (name) => `${toPascalCase(name)}IT` },
      { label: 'Mock', getValue: (name) => `${toPascalCase(name)}Mock` },
      { label: 'Fixture', getValue: (name) => `${toPascalCase(name)}Fixture` },
      { label: 'Java 文件', getValue: (name) => `${toPascalCase(name)}.java` },
      { label: '测试文件', getValue: (name) => `${toPascalCase(name)}Test.java` },
      { label: '属性前缀', getValue: (name) => toKebabCase(name) },
      { label: 'REST 路径', getValue: (name) => `/${toPluralKebabCase(name)}` },
      { label: '权限码', getValue: (name) => toDotCase(name) },
    ],
  },
  {
    title: 'Python',
    items: [
      { label: '变量', getValue: (name) => toSnakeCase(name) },
      { label: '函数', getValue: (name) => toSnakeCase(name) },
      { label: '异步函数', getValue: (name) => `async_${toSnakeCase(name)}` },
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: '模块常量', getValue: (name) => toConstantCase(name) },
      { label: '私有成员', getValue: (name) => `_${toSnakeCase(name)}` },
      { label: '强私有成员', getValue: (name) => `__${toSnakeCase(name)}` },
      { label: '魔术方法', getValue: (name) => `__${toSnakeCase(name)}__` },
      { label: '属性', getValue: (name) => toSnakeCase(name) },
      { label: 'property', getValue: (name) => toSnakeCase(name) },
      { label: '模块文件', getValue: (name) => `${toSnakeCase(name)}.py` },
      { label: '包目录', getValue: (name) => toSnakeCase(name) },
      { label: '测试文件', getValue: (name) => `test_${toSnakeCase(name)}.py` },
      { label: 'pytest 用例', getValue: (name) => `test_${toSnakeCase(name)}` },
      { label: 'fixture', getValue: (name) => `${toSnakeCase(name)}_fixture` },
      { label: 'Mock', getValue: (name) => `${toSnakeCase(name)}_mock` },
      { label: 'Factory', getValue: (name) => `${toPascalCase(name)}Factory` },
      { label: 'Pydantic 模型', getValue: (name) => `${toPascalCase(name)}Model` },
      { label: 'Schema', getValue: (name) => `${toPascalCase(name)}Schema` },
      { label: 'CreateSchema', getValue: (name) => `${toPascalCase(name)}Create` },
      { label: 'UpdateSchema', getValue: (name) => `${toPascalCase(name)}Update` },
      { label: 'ReadSchema', getValue: (name) => `${toPascalCase(name)}Read` },
      { label: 'Settings', getValue: (name) => `${toPascalCase(name)}Settings` },
      { label: 'SQLAlchemy 模型', getValue: (name) => `${toPascalCase(name)}Table` },
      { label: 'Repository', getValue: (name) => `${toSnakeCase(name)}_repository` },
      { label: 'Service', getValue: (name) => `${toSnakeCase(name)}_service` },
      { label: 'Router', getValue: (name) => `${toSnakeCase(name)}_router` },
      { label: 'Dependency', getValue: (name) => `get_${toSnakeCase(name)}` },
      { label: 'Middleware', getValue: (name) => `${toSnakeCase(name)}_middleware` },
      { label: 'Exception', getValue: (name) => `${toPascalCase(name)}Error` },
      { label: 'Enum', getValue: (name) => `${toPascalCase(name)}Enum` },
      { label: 'Protocol', getValue: (name) => `${toPascalCase(name)}Protocol` },
      { label: 'TypedDict', getValue: (name) => `${toPascalCase(name)}Dict` },
      { label: 'Dataclass', getValue: (name) => `${toPascalCase(name)}Data` },
      { label: 'Celery 任务', getValue: (name) => `${toSnakeCase(name)}_task` },
      { label: '管理命令', getValue: (name) => toSnakeCase(name) },
      { label: 'Alembic 迁移', getValue: (name) => `create_${toPluralSnakeCase(name)}_table` },
      { label: 'FastAPI 路由', getValue: (name) => `/${toKebabCase(name)}` },
      { label: '动态路由', getValue: (name) => `/${toKebabCase(name)}/{${toSnakeCase(name)}_id}` },
      { label: '查询参数', getValue: (name) => toSnakeCase(name) },
      { label: '环境变量', getValue: (name) => toConstantCase(name) },
      { label: '日志字段', getValue: (name) => toSnakeCase(name) },
      { label: 'CLI 命令', getValue: (name) => toKebabCase(name) },
    ],
  },
  {
    title: 'PHP',
    items: [
      { label: '变量', getValue: (name) => `$${toCamelCase(name)}` },
      { label: '方法', getValue: (name) => toCamelCase(name) },
      { label: '函数', getValue: (name) => toSnakeCase(name) },
      { label: '类名', getValue: (name) => toPascalCase(name) },
      { label: '接口', getValue: (name) => `${toPascalCase(name)}Interface` },
      { label: 'Trait', getValue: (name) => `${toPascalCase(name)}Trait` },
      { label: 'Enum', getValue: (name) => `${toPascalCase(name)}Enum` },
      { label: '命名空间', getValue: (name) => toPascalCase(name) },
      { label: '常量', getValue: (name) => toConstantCase(name) },
      { label: 'Controller', getValue: (name) => `${toPascalCase(name)}Controller` },
      { label: 'ApiController', getValue: (name) => `${toPascalCase(name)}ApiController` },
      { label: 'Service', getValue: (name) => `${toPascalCase(name)}Service` },
      { label: 'Repository', getValue: (name) => `${toPascalCase(name)}Repository` },
      { label: 'Model', getValue: (name) => `${toPascalCase(name)}Model` },
      { label: 'Entity', getValue: (name) => `${toPascalCase(name)}Entity` },
      { label: 'DTO', getValue: (name) => `${toPascalCase(name)}Data` },
      { label: 'Request', getValue: (name) => `${toPascalCase(name)}Request` },
      { label: 'FormRequest', getValue: (name) => `${toPascalCase(name)}FormRequest` },
      { label: 'Resource', getValue: (name) => `${toPascalCase(name)}Resource` },
      { label: 'Collection', getValue: (name) => `${toPascalCase(name)}Collection` },
      { label: 'Middleware', getValue: (name) => `${toPascalCase(name)}Middleware` },
      { label: 'Policy', getValue: (name) => `${toPascalCase(name)}Policy` },
      { label: 'Gate', getValue: (name) => `${toCamelCase(name)}Gate` },
      { label: 'Job', getValue: (name) => `${toPascalCase(name)}Job` },
      { label: 'Command', getValue: (name) => `${toPascalCase(name)}Command` },
      { label: 'Event', getValue: (name) => `${toPascalCase(name)}Event` },
      { label: 'Listener', getValue: (name) => `${toPascalCase(name)}Listener` },
      { label: 'Notification', getValue: (name) => `${toPascalCase(name)}Notification` },
      { label: 'Mail', getValue: (name) => `${toPascalCase(name)}Mail` },
      { label: 'Observer', getValue: (name) => `${toPascalCase(name)}Observer` },
      { label: 'Provider', getValue: (name) => `${toPascalCase(name)}ServiceProvider` },
      { label: 'Rule', getValue: (name) => `${toPascalCase(name)}Rule` },
      { label: 'Cast', getValue: (name) => `${toPascalCase(name)}Cast` },
      { label: 'Scope', getValue: (name) => `${toPascalCase(name)}Scope` },
      { label: 'Factory', getValue: (name) => `${toPascalCase(name)}Factory` },
      { label: 'Seeder', getValue: (name) => `${toPascalCase(name)}Seeder` },
      { label: 'Migration', getValue: (name) => `create_${toPluralSnakeCase(name)}_table` },
      { label: 'Exception', getValue: (name) => `${toPascalCase(name)}Exception` },
      { label: '测试类', getValue: (name) => `${toPascalCase(name)}Test` },
      { label: 'FeatureTest', getValue: (name) => `${toPascalCase(name)}FeatureTest` },
      { label: 'UnitTest', getValue: (name) => `${toPascalCase(name)}UnitTest` },
      { label: 'PHP 文件', getValue: (name) => `${toPascalCase(name)}.php` },
      { label: 'Blade 文件', getValue: (name) => `${toKebabCase(name)}.blade.php` },
      { label: '路由名', getValue: (name) => toDotCase(name) },
      { label: '路由路径', getValue: (name) => `/${toKebabCase(name)}` },
      { label: '配置键', getValue: (name) => toDotCase(name) },
      { label: 'Env 变量', getValue: (name) => toConstantCase(name) },
      { label: '队列名', getValue: (name) => toKebabCase(name) },
    ],
  },
  {
    title: 'SQL',
    items: [
      { label: '数据库', getValue: (name) => toSnakeCase(name) },
      { label: 'Schema', getValue: (name) => toSnakeCase(name) },
      { label: '表名', getValue: (name) => toPluralSnakeCase(name) },
      { label: '关联表', getValue: (name) => `${toPluralSnakeCase(name)}_relations` },
      { label: '字段名', getValue: (name) => toSnakeCase(name) },
      { label: '主键', getValue: (name) => `${toSnakeCase(name)}_id` },
      { label: '外键', getValue: (name) => `${toSnakeCase(name)}_id` },
      { label: '布尔字段', getValue: (name) => `is_${toSnakeCase(name)}` },
      { label: '状态字段', getValue: (name) => `${toSnakeCase(name)}_status` },
      { label: '类型字段', getValue: (name) => `${toSnakeCase(name)}_type` },
      { label: '数量字段', getValue: (name) => `${toSnakeCase(name)}_count` },
      { label: '金额字段', getValue: (name) => `${toSnakeCase(name)}_amount` },
      { label: '时间字段', getValue: (name) => `${toSnakeCase(name)}_at` },
      { label: '日期字段', getValue: (name) => `${toSnakeCase(name)}_date` },
      { label: 'JSON 字段', getValue: (name) => `${toSnakeCase(name)}_json` },
      { label: '普通索引', getValue: (name) => `idx_${toSnakeCase(name)}` },
      { label: '联合索引', getValue: (name) => `idx_${toSnakeCase(name)}_id` },
      { label: '唯一索引', getValue: (name) => `uk_${toSnakeCase(name)}` },
      { label: '主键约束', getValue: (name) => `pk_${toSnakeCase(name)}` },
      { label: '外键约束', getValue: (name) => `fk_${toSnakeCase(name)}_id` },
      { label: '唯一约束', getValue: (name) => `uq_${toSnakeCase(name)}` },
      { label: '检查约束', getValue: (name) => `ck_${toSnakeCase(name)}` },
      { label: '默认约束', getValue: (name) => `df_${toSnakeCase(name)}` },
      { label: '查询别名', getValue: (name) => toSnakeCase(name) },
      { label: 'CTE', getValue: (name) => `${toSnakeCase(name)}_cte` },
      { label: '视图', getValue: (name) => `v_${toSnakeCase(name)}` },
      { label: '物化视图', getValue: (name) => `mv_${toSnakeCase(name)}` },
      { label: '存储过程', getValue: (name) => `sp_${toSnakeCase(name)}` },
      { label: '函数', getValue: (name) => `fn_${toSnakeCase(name)}` },
      { label: '触发器', getValue: (name) => `trg_${toSnakeCase(name)}` },
      { label: '序列', getValue: (name) => `seq_${toSnakeCase(name)}` },
      { label: '临时表', getValue: (name) => `tmp_${toSnakeCase(name)}` },
      { label: '归档表', getValue: (name) => `${toSnakeCase(name)}_archive` },
      { label: '备份表', getValue: (name) => `${toSnakeCase(name)}_bak` },
      { label: '日志表', getValue: (name) => `${toSnakeCase(name)}_logs` },
      { label: '历史表', getValue: (name) => `${toSnakeCase(name)}_histories` },
      { label: '审计表', getValue: (name) => `${toSnakeCase(name)}_audits` },
      { label: '分区表', getValue: (name) => `${toSnakeCase(name)}_partition` },
      { label: '迁移', getValue: (name) => `create_${toPluralSnakeCase(name)}_table` },
      { label: '种子数据', getValue: (name) => `seed_${toPluralSnakeCase(name)}` },
      { label: '回滚脚本', getValue: (name) => `drop_${toPluralSnakeCase(name)}_table` },
      { label: 'SQL 文件', getValue: (name) => `${toSnakeCase(name)}.sql` },
    ],
  },
];

  return namingGroupList;
};
